$("document").ready(function(){
    $('.project_button').click(function(){
        if($('.globe_portfolio').html()!=null){
            $('.globe_portfolio').slideUp('slow',function(){
                $('.globe_portfolio').remove();
            });
        }
        else{
            project_box($(this).attr('id'),$(this).attr('position'),$(this).parent());
        }
    });
});